ver 1
go-park-mail-ru/2021_1_LioKor pull request #2
Opened 2021-03-03 20:28 UTC by altanab

Чистая архитектура
Регистрация
Аутентификация
Изменение профиля

2021-03-03 20:49 UTC, hackallcode commented on internal/app/server/server.go
> +	}
Наверное будет лучше записать репозиторий и юзкейс в отдельные переменные, так будет читаемее

2021-03-03 20:49 UTC, hackallcode commented on internal/pkg/user/models.go
> +	Name string
Может это message, а не name?)

2021-03-03 20:49 UTC, hackallcode commented on go.mod
> +module github.com/go-park-mail-ru/2021_1_LioKor
Давай сделаем название аля liokor_mail, пути везде будут красивее и не будет возникать ощущение, что ты используешь старый вариант подтягивания зависимостей без го модулей

2021-03-03 20:55 UTC, hackallcode commented on main.go
> +package main
А давай все main файлы хранить в папочке cmd
Например, этот в cmd/имя_прилоожения/main.go положить можно
Потом будет много микросервисов, так что будут пути cmd/имя_сервиса/main.go

2021-03-09 19:01 UTC, hackallcode requested changes

2021-03-09 19:01 UTC, hackallcode commented on cmd/main/config.json
> +        "https://api.mail.liokor.ru"
У вас апи ходит в апи? Если нет, то зачем это?

2021-03-09 19:01 UTC, hackallcode commented on cmd/main/config.json
> +    "port": "8000",
Думаю можно сделать порт не строкой, а числом)

2021-03-09 19:01 UTC, hackallcode commented on internal/app/server/server.go
> +	e.Logger.Fatal(e.Start(host + ":" + port))
А что если мы погасим сервер аккуратно, gracefull? Тоже фатал?

2021-03-09 19:01 UTC, hackallcode commented on internal/pkg/user/repository/repository.go
> +package repository
Может назовем этот файл memory.go? О том, что это репозиторий, говорит название папки, а название папки должно показывать способ хранения данных

2021-03-09 19:01 UTC, hackallcode commented on internal/pkg/user/usecase/usecase.go
> +}
В целом по логике это не относится к юзкейсу пользователя, так что можно вынести в какую-нибудь папочку аля internal/pkg/helpers, utils, common...

2021-03-09 19:01 UTC, hackallcode commented on internal/pkg/user/validators/validators.go
> +func ValidateUsername(username string) bool {
А другие данные валидировать не надо? Например, то что пароль только из английских букв.

2021-03-09 19:14 UTC, KoroLion commented on cmd/main/config.json
> +        "https://api.mail.liokor.ru"
там swagger размещён, мб ему там не место... Есть 2 варианта:

1. https://api.mail.liokor.ru/api/swagger (в будущем без /api в конце)
2. https://mail.liokor.ru/api/swagger

2021-03-09 19:15 UTC, KoroLion commented on internal/pkg/user/validators/validators.go
> +func ValidateUsername(username string) bool {
мы решили валидировать пароль только JSом: если пользователь ОЧЕНЬ хочет себе слабый пароль (так сильно, что отключит проверку), то пусть ставит.

2021-03-09 19:16 UTC, hackallcode commented on cmd/main/config.json
> +        "https://api.mail.liokor.ru"
Первый логичнее, так как информация о бэке должна быть на бэке. Плюс в пределах одного домена наюе надо будет делать CORS, так что подходит и в этом плане

2021-03-09 19:18 UTC, hackallcode commented on internal/pkg/user/validators/validators.go
> +func ValidateUsername(username string) bool {
Нельзя давать такую возможно пользователю, даже если он очень хочет. Все проверки должны быть и на фронте, и на бэке

2021-03-09 19:18 UTC, KoroLion commented on cmd/main/config.json
> +        "https://api.mail.liokor.ru"
точно: api.mail.liokor.ru по любому не должно быть в этом списке

2021-03-09 19:19 UTC, KoroLion commented on internal/pkg/user/validators/validators.go
> +func ValidateUsername(username string) bool {
но ведь это не влияет на других, в отличие от плохого юзернейма

2021-03-09 19:20 UTC, hackallcode commented on cmd/main/config.json
> +        "https://api.mail.liokor.ru"
Именно, только если у вас каким-то образом бэк не поделен на два домена

2021-03-09 19:20 UTC, hackallcode commented on internal/pkg/user/validators/validators.go
> +func ValidateUsername(username string) bool {
Все равно, в случае, например, пароля, безопасность системы снижается

2021-03-09 19:22 UTC, hackallcode commented on internal/pkg/user/validators/validators.go
> +func ValidateUsername(username string) bool {
Например, какой-нибудь "крутой" админ решил обойти валидацию и поставить себе пароль "123". В итоге будущий хакер попробует прогнать самые частые пароли (среди которых есть 123) и получит административный доступ к системе

2021-03-09 20:06 UTC, KoroLion commented on internal/pkg/user/validators/validators.go
> +func ValidateUsername(username string) bool {
хороший аргумент - добавим валидацию

2021-03-10 21:17 UTC, hackallcode commented on internal/pkg/user/delivery/handler.go
>  	c.SetCookie(&http.Cookie{
Мне кажется удаление куки тоже можно вынести в отдельную функцию и при НЕ успешной проверке авторизованности (некорректный ID сессии, например), сбрасывать куку

2021-03-10 21:34 UTC, hackallcode approved these changes
Прекрасный патч!

2021-03-10 21:34 UTC, merged