echo server
go-park-mail-ru/2021_1_LioKor pull request #3
Opened 2021-03-04 16:56 UTC by altanab

2021-03-04 17:02 UTC, hackallcode requested changes

2021-03-04 17:02 UTC, hackallcode commented on go.mod
> +module lioKor_mail
LioKorMail
или
lio_kor_mail

А то стили смешались

2021-03-04 17:02 UTC, hackallcode commented on internal/app/server/server.go
> +	rep := &repository.UserRepository{
user_rep, чтобы в будущем можно было сделать несколько репозиьториев

2021-03-04 17:02 UTC, hackallcode commented on internal/app/server/server.go
> +	uc := &usecase.UserUseCase{rep}
user_uc

2021-03-05 08:49 UTC, KoroLion commented on go.mod
> +module lioKor_mail
liokor_mail

2021-03-09 18:44 UTC, merged